#!/usr/bin/env bash

# Is there anything lingering
brew cleanup

# Tap third-party formulae
brew tap caskroom/versions

# Update Repositories
brew update

# AWS Shell
brew install awscli
brew install aws-shell

# Utilities
brew install dos2unix
brew install geoip
brew install htop
brew install calc
brew install ncdu
brew install nmap
brew install wget
brew install tree
brew install youtube-dl
brew install irssi